PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX aiiso: <http://purl.org/vocab/aiiso/schema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?instituicao (COUNT(?curso) as ?quant_cursos)
WHERE {
        ?curso a aiiso:Programme.
        ?curso foaf:name ?curso_name.
        ?curso aiiso:part_of ?instituicao.
        ?instituicao a dbo:EducationalInstitution.
        FILTER regex(lcase(?curso_name), "engenharia")   
}
GROUP BY ?instituicao
ORDER BY DESC (?quant_cursos)


PREFIX  cin:<http://purl.org/ontology/opencin/>
SELECT (COUNT(*) as ?Triples)
WHERE { ?s a cin:Student. }


PREFIX  dbo:<http://dbpedia.org/ontology/>
SELECT (COUNT(*) as ?Triples)
WHERE { ?s a dbo:Professor. }
  
  
PREFIX aiiso: <http://purl.org/vocab/aiiso/schema#>
SELECT (COUNT(*) as ?Triples)
WHERE { ?s a aiiso:Programme. }

PREFIX aiiso: <http://purl.org/vocab/aiiso/schema#>
SELECT (COUNT(*) as ?Triples)
WHERE { ?s a aiiso:Center. }










PREFIX  foaf: <http://xmlns.com/foaf/0.1/>

SELECT ?name ?cursoname
WHERE {
  ?subject a <http://purl.org/ontology/opencin/Student>.
  ?subject <http://purl.org/ontology/opencin/belongsA> ?curso.
  ?subject foaf:name ?name.
  ?curso foaf:name ?cursoname.
}
LIMIT 25




PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX aiiso: <http://purl.org/vocab/aiiso/schema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?instituicao (COUNT(?s) as ?triplas)
WHERE {
		?s ?p ?instituicao.
        ?instituicao a dbo:EducationalInstitution. 
}
GROUP BY ?instituicao
ORDER BY DESC (?triplas)