
CURSO="curso"
DEPARTAMENTO="departamento"

IFRN=""
IFMA=""
IFPA=""
UFRN=""
IFS=""
IFMS=""
UFCSPA=""
UFV=""
UFCA=""
UFPI=""
UFSJ=""
IFPB=""
UNIRIO=""
UFFS=""
UFPB=""
UNIFESSPA="http://dbpedia.org/page/Federal_University_of_Southern_and_Southeastern_Par%C3%A1"
UFMA=""
UFPEL=""
IFFAR=""
UFMS=""
UFOP="http://dbpedia.org/resource/Federal_University_of_Ouro_Preto"